import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { logger } from '@/lib/logger';

/*{
    Function Name: GET
    Purpose: Fetch all clients from the database
    Parameters: None
}*/
export async function GET() {
  try {
    let timeoutHandle: NodeJS.Timeout;
    const timeoutPromise = new Promise((_, reject) => {
      timeoutHandle = setTimeout(() => reject(new Error('Supabase query timed out')), 10000);
    });

    try {
      const { data: clients, error } = await Promise.race([
        supabase
          .from('clients')
          .select('*')
          .order('business_name', { ascending: true }),
        timeoutPromise
      ]) as any;

      clearTimeout(timeoutHandle!);

      if (error) {
        logger.error('Fetch Clients Error', error);
        return NextResponse.json({ error: 'Failed to fetch clients' }, { status: 500 });
      }

      return NextResponse.json(clients);
    } catch (raceError) {
      clearTimeout(timeoutHandle!);
      throw raceError;
    }
  } catch (error) {
    logger.error('Fetch Clients Unexpected Error', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

/*{
    Function Name: POST
    Purpose: Creates a new client in the system
    Parameters: request (NextRequest)
}*/
export async function POST(request: NextRequest) {
  try {
    const { business_name, whatsapp_phone_number_id, access_token } = await request.json();

    // 1. Validate required fields
    if (!business_name || !whatsapp_phone_number_id || !access_token) {
      return NextResponse.json(
        { error: 'Missing required fields: business_name, whatsapp_phone_number_id, and access_token are required' },
        { status: 400 }
      );
    }

    // 2. Insert new client into the database
    // The id and created_at will be automatically generated by Supabase
    const { data, error } = await supabase
      .from('clients')
      .insert({
        business_name,
        whatsapp_phone_number_id,
        access_token
      })
      .select()
      .single();

    // 3. Handle database errors
    if (error) {
      logger.error('Error creating client', error);
      
      // Handle unique constraint violation for whatsapp_phone_number_id
      if (error.code === '23505') {
        return NextResponse.json(
          { error: 'A client with this WhatsApp Phone Number ID already exists' },
          { status: 409 }
        );
      }

      return NextResponse.json(
        { error: 'Failed to create client in database' },
        { status: 500 }
      );
    }

    // 4. Log success and return data
    logger.info('Client created successfully', { 
      id: data.id, 
      business_name: data.business_name 
    });

    return NextResponse.json(
      { message: 'Client created successfully', client: data },
      { status: 201 }
    );
  } catch (error) {
    logger.error('Internal Server Error in Client POST API', error);
    return NextResponse.json(
      { error: 'Internal Server Error' },
      { status: 500 }
    );
  }
}
